version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        environment: 
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:3000"
